name: Prod deployment

on: [push]

jobs:
  prod-agent-deployment:
    name: Build and upload agent
    runs-on: self-hosted
    container: golang:1.16
    env:
      BASE_NAME: spacelift-vcs-agent
      BIN_DIR: build

    steps:
      - name: Check out repository code
        uses: actions/checkout@master

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.5.8
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-external-id: ${{ secrets.AWS_EXTERNAL_ID }}
          role-duration-seconds: 900

      - uses: chrnorm/deployment-action@releases/v1
        name: Create GitHub deployment
        if: github.ref == 'refs/heads/production'
        id: deployment
        with:
          token: "${{ github.token }}"
          target_url: https://downloads.spacelift.io/spacelift-vcs-agent
          environment: prod/vcs-agent

      - name: parse short SHA
        id: vars
        run: |
          echo ::set-output name=sha::$(git rev-parse --short=8 ${{ github.sha }})

      - name: Build Spacelift VCS Agent
        run: go build -a -tags netgo -ldflags '-s -w -extldflags "-static"' -trimpath -o $BIN_DIR/$BASE_NAME ./cmd/spacelift-vcs-agent
        env:
          CGO_ENABLED: 0
          SHORT_SHA: ${{ steps.vars.outputs.sha }}

      - name: Install dependencies
        run: |
          apt-get update -y
          apt-get install -y awscli zip

      - name: Import the PGP key
        run: |
          echo ${GPG_KEY_BASE64} | base64 -d > spacelift.gpg
          gpg --import \
            --passphrase=$GPG_PASSPHRASE \
            --pinentry-mode=loopback \
            spacelift.gpg
          rm spacelift.gpg
        env:
          GPG_KEY_BASE64: ${{ secrets.GPG_KEY_BASE64 }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Sign Spacelift VCS Agent Binary
        run: ./scripts/sign.sh $BIN_DIR $BASE_NAME
        env:
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          SHORT_SHA: ${{ steps.vars.outputs.sha }}

      - name: Verify Checksum Spacelift VCS Agent Binary
        run: ./scripts/verify.sh $BIN_DIR $BASE_NAME
        env:
          SHORT_SHA: ${{ steps.vars.outputs.sha }}


      - name: Upload the VCS Agent binary to downloads.spacelift.io (dry run)
        if: github.ref != 'refs/heads/production'
        run: >-
          aws s3 sync
          ${BIN_DIR} s3://${{ secrets.AWS_S3_BUCKET }}/
          --dryrun
          --no-progress

      - name: Upload the VCS Agent binary to downloads.spacelift.io
        if: github.ref == 'refs/heads/production'
        run: >-
          aws s3 sync
          ${BIN_DIR} s3://${{ secrets.AWS_S3_BUCKET }}/
          --no-progress

      - name: Invalidate downloads.spacelift.io cache
        if: github.ref == 'refs/heads/production'
        run: >-
          aws cloudfront create-invalidation
          --distribution-id ${{ secrets.DISTRIBUTION }}
          --paths "/*"

      - name: Update deployment status (success)
        uses: chrnorm/deployment-status@releases/v1
        if: success() && github.ref == 'refs/heads/production'
        with:
          token: "${{ github.token }}"
          target_url: https://downloads.spacelift.io/spacelift-vcs-agent
          state: "success"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}

      - name: Update deployment status (failure)
        uses: chrnorm/deployment-status@releases/v1
        if: failure() && github.ref == 'refs/heads/production'
        with:
          token: "${{ github.token }}"
          target_url: https://downloads.spacelift.io/spacelift-vcs-agent
          state: "failure"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
